version: "3"

services:
  db-service:
    build: ./db
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  api-service:
    build: ./app
    volumes:
      - ./app:/usr/src/app
    ports:
      - 8888:8000
    depends_on:
      - db-service